### PR TITLE
Make peerDependencies match RSC versions

### PR DESCRIPTION
**Pull request by karlhorky**
Hi @phryneas, thanks for the work you've put into making the Apollo packages work with RSC, amazing!

Just wanted to do a quick PR to set a minimum version for the `react` and `@types/react` peer deps (`peerDependencies` are installed by pnpm and npm)

This avoids situations where pnpm will resolve `@types/react` to the lowest possible common denominator, leading to a `pnpm-lock.yaml` in a Next.js project like this (`@types/react@18.0.0` was installed):

```yaml
dependencies:
  '@apollo/client':
    specifier: ^3.9.5
    version: 3.9.5(@types/react@18.0.0)(graphql@16.8.1)(react-dom@18.0.0)(react@18.0.0)
```

@Eprince-hub had this during one of our lectures, and it caused the types for `cache` and other later React features to break.

### CODE REVIEW

**Comment by phryneas** [comment]
Hm, can you explain a bit more where that matters? 

Next.js brings it's own React version and will ignore the one in `node_modules`, and this package will accept that.

Also, `rehackt` will potentially be used with older React versions thatn 18.2, since Apollo Client has it as a dependency and that one works with even 16.x versions of React.

There's also the point that Rehackt has to work with experimental and canary React builds, which start with `0.0.0`.

**Comment by phryneas** [comment]
I believe we could do something like
```
"react": "^16.8.0 || ^17.0.0 || ^18.0.0 || >18.3.0-canary || >18.3.0-next || >0.0.0-experimental || >0.0.0-phryneas",
"@types/react": "^16.8.0 || ^17.0.0 || ^18.0.0"
```
or maybe shorter (?)
```
"react": ">0.0.0-a",
"@types/react": "^16.8.0 || ^17.0.0 || ^18.0.0"
```
but would that actually help you?

**Comment by phryneas** [comment]
But yeah, it seems that * is not compatible with the [semver spec](https://semver.org/) . I'll look into this tomorrow.

**Comment by karlhorky** [comment]
> Hm, can you explain a bit more where that matters?

The issue we encountered during the lecture was that the `rehackt` peer dependency `"@types/react": "*"` plus the devDependency created by `create-next-app` of `"@types/react": "^18"` resulted in a `@types/react` version of `18.0.0`, which broke the imports of the newer features such as `import { cache } from 'react';` and the Server Actions `formAction` prop.

But maybe my PR here is invalid: I thought `rehackt` was meant to be used only for RSC, based on the description of the package:

https://github.com/phryneas/rehackt/blob/0e6704c5d57402e2e2f54544dbf1901d642cf083/package.json#L4

**Comment by karlhorky** [comment]
Maybe the `*` is the most valid version specifier in this case, seems like it is in [the npm semver docs](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept):

> For example, to specify acceptable version ranges up to 1.0.4, use the following syntax:
> 
> - Patch releases: 1.0 or 1.0.x or ~1.0.4
> - Minor releases: 1 or 1.x or ^1.0.4
> - Major releases: * or x

**Comment by phryneas** [comment]
> But maybe my PR here is invalid: I thought rehackt was meant to be used only for RSC, based on the description of the package:

Yes and no. Rehackt is a drop-in "replacement" for `react` that fixes bunding issue if you are in a RSC environment. 
In a non-RSC environment it can still be installed and used as a dependency instead of `react`, but it won't do anything extra - it just reexports `react`, which has to be installed alongside.

Since we have to choose the dependency to import statically, and we have the choice between `react` that breaks in some situations and `rehackt` that resolves those situations and just "does nothing" in any other situation, the choice for `@apollo/client` is to go with importing from `rehackt` and having `react` as a `peerDepenency` that will be exposed (with workarounds, if needed) through `rehackt`.

**Comment by phryneas** [comment]
> Maybe the `*` is the most valid version specifier in this case, seems like it is in [the npm semver docs](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept):

That's very curious, seeing that it is not mentioned in the semver spec :/

**Comment by karlhorky** [comment]
For completeness, here's also the issue that @Eprince-hub created in `create-next-app`:

- https://github.com/vercel/next.js/pull/62334

Looks like the original issue was also caused by an older version of `pnpm` (pre-`8.7.0`), which selected the lowest possible version.

`pnpm@>=8.7.0` should automatically should actually resolve to the highest possible version by default now:

- https://github.com/pnpm/pnpm/issues/6463
- [twitter.com/pnpmjs/status/1693707270897517022](https://twitter.com/pnpmjs/status/1693707270897517022)
- https://github.com/pnpm/pnpm/pull/6987

So, this is probably not as common either.

I'll close this out for now, thanks for the discussion!

**Comment by karlhorky** [comment]
> Yes and no. Rehackt is a drop-in "replacement" for `react` that fixes bunding issue if you are in a RSC environment. In a non-RSC environment it can still be installed and used as a dependency instead of `react`, but it won't do anything extra - it just reexports `react`, which has to be installed alongside.
> 
> Since we have to choose the dependency to import statically, and we have the choice between `react` that breaks in some situations and `rehackt` that resolves those situations and just "does nothing" in any other situation, the choice for `@apollo/client` is to go with importing from `rehackt` and having `react` as a `peerDepenency` that will be exposed (with workarounds, if needed) through `rehackt`.

Oh very interesting, thanks for the background!

**Comment by phryneas** [comment]
Great to hear that you got it resolved with a bundler update!

And thanks for the PR and bringing this up - I'm sure it will be helpful to someone else in the future :)

**Pull request closed without merging**
